version: '3.6'

services:
  backend:
    image: kordondev/equipment-watchdog
    container_name: ew-backend
    ports:
      - "8080:8081"
    restart: always
    volumes:
      - ${PWD}/configuration:/configuration

