version: '3.6'

services:
  backend:
    image: ghcr.io/kordondev/equipment-watchdog-backend
    container_name: equipment-watchdog-backend
    ports:
      - "8080:8080"
    volumes:
      - ./configuration:/configuration:ro
      - ./equipment-watchdog.db:/equipment-watchdog.db
    restart: always

  frontend:
    image: ghcr.io/kordondev/equipment-watchdog-frontend
    container_name: equipment-watchdog-frontend
    restart: always
    ports:
      - "1080:80"
    environment:
      - URL=http://localhost:8080
